# Form implementation generated from reading ui file 'add_channel_window.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_add_channel(object):
    def setupUi(self, add_channel):
        add_channel.setObjectName("add_channel")
        add_channel.resize(400, 151)
        self.formLayout_2 = QtWidgets.QFormLayout(add_channel)
        self.formLayout_2.setObjectName("formLayout_2")
        self.name_label = QtWidgets.QLabel(add_channel)
        self.name_label.setObjectName("name_label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.name_label)
        self.name_edit = QtWidgets.QLineEdit(add_channel)
        self.name_edit.setObjectName("name_edit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.name_edit)
        self.url_label = QtWidgets.QLabel(add_channel)
        self.url_label.setObjectName("url_label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.url_label)
        self.url_edit = QtWidgets.QLineEdit(add_channel)
        self.url_edit.setClearButtonEnabled(True)
        self.url_edit.setObjectName("url_edit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.url_edit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_button = QtWidgets.QPushButton(add_channel)
        self.add_button.setObjectName("add_button")
        self.horizontalLayout.addWidget(self.add_button)
        self.cancel_button = QtWidgets.QPushButton(add_channel)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.formLayout_2.setLayout(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout)

        self.retranslateUi(add_channel)
        QtCore.QMetaObject.connectSlotsByName(add_channel)

    def retranslateUi(self, add_channel):
        _translate = QtCore.QCoreApplication.translate
        add_channel.setWindowTitle(_translate("add_channel", "Add Channel"))
        self.name_label.setText(_translate("add_channel", "Name:"))
        self.url_label.setText(_translate("add_channel", "Url:"))
        self.url_edit.setPlaceholderText(_translate("add_channel", "https://www.youtube.com/c/ChannelName/"))
        self.add_button.setText(_translate("add_channel", "Add"))
        self.cancel_button.setText(_translate("add_channel", "Cancel"))
