# Form implementation generated from reading ui file 'add_channel_window.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_add_channel(object):
    def setupUi(self, add_channel):
        add_channel.setObjectName("add_channel")
        add_channel.resize(400, 110)
        self.verticalLayout = QtWidgets.QVBoxLayout(add_channel)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.name_label = QtWidgets.QLabel(add_channel)
        self.name_label.setObjectName("name_label")
        self.gridLayout.addWidget(self.name_label, 0, 0, 1, 1)
        self.name_edit = QtWidgets.QLineEdit(add_channel)
        self.name_edit.setObjectName("name_edit")
        self.gridLayout.addWidget(self.name_edit, 0, 1, 1, 1)
        self.url_label = QtWidgets.QLabel(add_channel)
        self.url_label.setObjectName("url_label")
        self.gridLayout.addWidget(self.url_label, 1, 0, 1, 1)
        self.url_edit = QtWidgets.QLineEdit(add_channel)
        self.url_edit.setClearButtonEnabled(True)
        self.url_edit.setObjectName("url_edit")
        self.gridLayout.addWidget(self.url_edit, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(add_channel)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(add_channel)
        QtCore.QMetaObject.connectSlotsByName(add_channel)

    def retranslateUi(self, add_channel):
        _translate = QtCore.QCoreApplication.translate
        add_channel.setWindowTitle(_translate("add_channel", "Add Channel"))
        self.name_label.setText(_translate("add_channel", "Name:"))
        self.url_label.setText(_translate("add_channel", "Url:"))
        self.url_edit.setPlaceholderText(_translate("add_channel", "https://www.youtube.com/c/ChannelName/"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    add_channel = QtWidgets.QWidget()
    ui = Ui_add_channel()
    ui.setupUi(add_channel)
    add_channel.show()
    sys.exit(app.exec())
